### ISSUE TITLE
Clickable Link for Phone

### ISSUE THREAD

**Issue by Danitec** [pkerspe/ckeditor-bootstrap-accordionList#8]
I'd like to generate a Link for Smartphone like.
<p><a href="Tel:+4983217866020">Telefon: 08321 78 660 20</a></p>
On CK Editor this is working.
But AccordionList ist removing this Link by reopening.
In AccordionList are only http, https, news and ftp possible.

Where is this possible to change?

**Comment by pkerspe** [comment]
First of all "Telefon:" is not a valid protocol name. For phone numbers only "tel:" is considered valid according to RFC3966.
Will close this issue, since it is not really related to the plugin itself.
If you have any more issues with content being removed, you might want to have a look at the "allowedContent" section in the plugin.js file
